### ISSUE TITLE
Include an example of a SBOM

### ISSUE THREAD

**Issue by farnulfo** [eclipse/jbom#16]
Hi,

Could add an example of a SBOM in git repo to see what to expect as a result ?

**Comment by davewichers** [comment]
It's super easy to just generate one yourself. Clone this project, run mvn test in the project, then run (as an example):  java -jar target/jbom-1.2.1.jar -f target/jbom-1.2.1.jar. You have to change the version to whatever version you just built. And the output tells you where the generated sbom was created.  This example runs jbom against itself, generating an sbom for jbom.  Or if you don't have maven set up, just download the most recently published jar and run it agains itself with just Java (e.g., java -jar jbomVERSION.jar -f jbomVERSION.jar).

**Comment by planetlevel** [comment]
If you're interested in other examples... see https://github.com/CycloneDX/bom-examples

**Comment by planetlevel** [comment]
Or if you've done a build (mvn package), you can look in the /target/test to see jbom output for the test jar files in src/test/resources directory.
